spring:
    application:
        name: store-management-customers-and-products
    main:
        allow-circular-references: true
    datasource:
        url: jdbc:mariadb://localhost:3306/storedb
        username: root
        password: admin123

jwt:
    secret: my-secret-key
