spring:
    application:
        name: store-management-customers-and-products
    main:
        allow-circular-references: true
    datasource:
        url: jdbc:mariadb://db:3306/storedb
        username: user
        password: admin123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect

jwt:
    secret: my-secret-key
